# Generated by Django 5.2.1 on 2025-05-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default='', max_length=5)),
                ('book_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(default='', max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(default='staff', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('course', models.CharField(max_length=50)),
                ('adhaar_number', models.CharField(max_length=12)),
                ('child_id', models.CharField(default='0', max_length=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('mobile_number', models.CharField(max_length=10)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('classes', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('adhaar_number', models.CharField(max_length=12)),
                ('pay_scale', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Social Science', 'Social Science')], max_length=100)),
                ('marks_obtained', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='Base.student')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Base.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='Base.student')),
            ],
        ),
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Sanskrit', 'Sanskrit'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Social Science', 'Social Science')], max_length=50)),
                ('term', models.CharField(choices=[('Quarterly', 'Quarterly'), ('Half-Yearly', 'Half-Yearly'), ('Annual', 'Annual')], max_length=20)),
                ('theory_marks', models.PositiveIntegerField()),
                ('practical_marks', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marksheets', to='Base.student')),
            ],
            options={
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
    ]
