# Generated by Django 5.2.1 on 2025-06-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_item_exammarks_delete_marksheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSchools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=100)),
                ('schoolDiceCode', models.CharField(max_length=12)),
                ('schoodId', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('school_id', models.CharField(max_length=10)),
            ],
        ),
    ]
